<!DOCTYPE html>
<html>
<head>
	<title></title>
	<?php 
	include_once 'html_commons/main-header.php';
	include_once 'html_commons/new-side.php';
	?>
</head>
<body background="images/background.jpg">
<h1 style="color: #191970;"><big><big><b>Organ and Tissue Donation from Living Donors</b></big></big></h1>
<br><br>While most solid organ and tissue donations occur after the donor has died, some organs and tissues can be donated while the donor is alive. The first successful transplant in the U.S. was made possible by a living donor and took place in 1954. One twin donated a kidney to his identical twin brother. As a result of the growing need for organs for transplantation, living donation has increased as an alternative to deceased donation, and about 6,000 living donations take place each year. Most living donations happen among family members or between close friends. Some living donations take place between people unknown to each other.
<br><br><h2 style="color: #191970;" >Organ Donation</h2>
<br><br>Living individuals can donate one of the two kidneys and the remaining kidney provides the necessary function needed to remove waste from the body. Single kidney donation is the most frequent living donor procedure.
<br><br>A living donor can donate one of two lobes of their liver. This is possible because, just as skin cells grow new skin, liver cells in the remaining lobe of the liver grow or regenerate until the liver is almost its original size. This re-growth of the liver occurs in a short period of time in both the liver donor and liver recipient.
<br><br>It is also possible for living donors to donate a lung or part of a lung, part of the pancreas, or part of the intestines. Although these organs do not regenerate, both the donated portion of the organ and the portion remaining with the donor are fully functioning.
<br><br>Surprisingly, it is also possible for a living person to donate a heart, but only if he or she is receiving a replacement heart. This occurs only when it is determined that someone with severe lung disease and a normally functioning heart would have a greater chance of survival if he or she received a combined heart and lung transplant. As a result, the heart-lung recipient's own heart, if it is in good condition, is then donated to an individual who needs only a heart transplant.
<br><br><h2 style="color: #191970;">Tissue Donation</h2>
<br><br>Tissues donated by living donors are amnion, skin, and bone as well as blood, marrow, blood stem cells, and umbilical cord blood. The amnion is donated after childbirth, skin can be donated after certain surgeries, such as abdominoplasties, and bone after knee and hip replacements. A healthy body can easily replace some tissues such as blood or bone marrow. Blood is made up of white and red blood cells, platelets, and the serum that carries blood cells throughout the circulatory system. Bone marrow contains stem cells. In addition, stem cells found in circulating blood in adults and from the umbilical cord of a newborn also can be donated. Both blood and bone marrow can even be donated more than once since they are regenerated and replaced by the body after donation.
<br><br>Suitability to Donate
<br><br>Each potential living donor is evaluated to determine suitability to donate. The evaluation includes both the possible psychological response and physical response to the donation process. This is done to ensure that no adverse outcome, physical, psychological, or emotional, will occur before, during, or following the donation. Generally, living donors should be physically fit, in good health, between the ages of 18 and 60, and should not have or have had diabetes, cancer, high blood pressure, kidney disease, or heart disease.
<br><br>The decision to be a living donor must be weighed carefully as to the benefits versus the risks for both the donor and the recipient. Often, the recipient has very little risk because the transplant will be life saving. However, the healthy donor, does face the risk of an unnecessary major surgical procedure and recovery. Living donors may also face other risks. For example, a small percentage of patients have had problems maintaining life, disability, or medical insurance coverage at the same level and rate as previously. And, there can be financial concerns due to possible delays in returning to work because of unforeseen medical problems.
<br><br><h2 style="color: #191970;">Follow-up for Living Donors</h2>
<br><br>The National Institutes of Health is in the process of conducting a study to collect information on the outcomes of living donors over time. At present, follow-up reviews of living donors by some transplant centers show that living donors, on average, have done very well over the long term. However, there are some scientific questions regarding the effects of stress on the remaining organ. There could be subtle medical problems that do not develop until decades after the living donation that are not known at this time because living donation is a relatively new medical procedure. To ensure the safety of all living donors, it is critical that the long term results of the effects of living donation are studied further.
<br><br><h2 style="color: #191970;">The Decision to Donate</h2>
<br><br>The decision to be a living donor is a very personal one and the potential donor must consider the possibility of adverse health effects that could follow donation. In some cases, the decision also may take into consideration the lifesaving potential for a loved one who may be the transplant recipient.
<br><br>Because all of the effects, especially the long term effects, to the donor are not known at this time, the Federal government does not actively encourage anyone to be a living donor. The Federal government does recognize the wonderful benefit that this gift of life provides to the patient awaiting a transplant and has several ongoing programs to study, support, and protect the living donors who do choose to provide this gift.
<br><br>The decision to say yes to both organ donation after death and/or as a living donor is the focus of many ongoing and completed research projects conducted across the nation, many of which are supported by the Division of Transplantation, Health Resources and Services Administration, U.S. Department of Health and Human Services.
<br><br><h2 style="color: #191970;">Federal Assistance for Living Organ Donors</h2>
<br><br>In September 2006, HRSA awarded a cooperative agreement to the University of Michigan to establish a national program to provide reimbursement of travel and subsistence expenses to living organ donors who cannot afford these costs. In October 2007, the University of Michigan in partnership with the American Society of Transplant Surgeons launched the National Living Donor Assistance Center to help donors with travel, lodging, and meal expenses associated with the organ donation process. For more information visit the National Living Donor Assistance Center Web site  
<br><br>
</body>
</html>