<!DOCTYPE html>
<html>
<head>
	<title></title>
	<?php 
	include_once 'html_commons/main-header.php';
	include_once 'html_commons/new-side.php';
	?>
</head>
<body background="images/background.jpg"><big>
<h1 style="color: #8B0000"><b>Organ Donation: The Process</b></h1>
<br><b>Enrolling as a Donor:</b> The altruistic process of donation begins when people perform the simple act of indicating their consent to be a donor by enrolling in their state's donor registry. Most often this happens when obtaining or renewing a driver's license or by going on-line for those state registries that have an Internet registration capacity. Most people also tell their family they want to be a donor so their family member can support their decision when needed. Signing up to be a donor usually takes place many years before donation becomes a possibility.
<br><br><a href="registration.php"> Register to Become a Donor</a>
<br><br><b>Trying to Save a Life:</b> At some point, a potential donor is admitted to a hospital because of illness or accident. Most donors are victims of severe head trauma, a brain aneurysm or stroke. Healthcare professionals work hard and long, doing everything possible to save the patient's life while maintaining the patient on mechanical devices.
<br><br><b>Testing for Brain Death:</b> When the medical team has exhausted all possible lifesaving efforts and the patient is not responding, a physician will perform a series of tests, usually on multiple occasions, to determine if brain death has occurred. This is usually done by a neurosurgeon or neurologist in compliance with accepted medical practice and state law. Patients who are brain dead have no brain activity and cannot breathe on their own. Brain death is not coma. Brain death is death and it is irreversible.
<br><br><b>Alerting the OPO:</b> In compliance with federal regulations, a hospital notifies its local organ procurement organization (OPO) of every patient that has died or is nearing death. A hospital gives the OPO information about the deceased to confirm his or her potential to be a donor. If the patient is a potential candidate for donation, an OPO representative immediately travels to the hospital.
<br><br><b>Obtaining Consent:</b> The OPO representative will search the state's donor registry to see if the deceased had enrolled as a donor. If so, that will serve as legal consent. If the deceased had not registered and there was no other legal consent for donation such as a driver's license indicator, the OPO will seek consent from the next of kin. When consent is obtained, medical evaluation will continue, including obtaining the deceased's complete medical and social history from the family.
<br><br><b>Matching Donors with Recipients:</b> If the deceased's evaluation does not rule out donation, the OPO contacts the Organ Procurement and Transplantation Network (OPTN) to begin the search for matching recipients.
<br><br>The OPTN operates the national database of all patients in the U.S. waiting for a transplant. It is operated by the United Network for Organ Sharing (UNOS) under contract to the U.S. Department of Health and Human Services (HHS). A computer program matches donor organs with recipients based on certain characteristics. These include blood type, tissue type, height, and weight. The length of time the patient has been waiting, the severity of the patient's illness, and the distance between the donor's and the recipient's hospitals also figure into who is the best match for a specific organ. The list does not reference race, gender, income or social status. The OPTN computer system stores the matching information for all waiting patients and the OPO representative enters the same information for the donor.
<br><br>A list of patients (by organ type) who match the donor is generated. Each organ is offered to the first patient on the computer match list. The transplant surgeon may determine that the organ is medically suitable for that patient or may refuse the organ for a number of reasons, such as the patient is too sick to be transplanted or the patient cannot be reached in time. Most organs (75%) go to local patients. The others are shared with patients in other regions of the country.
<br><br><b>Maintaining the Donor:</b> Meanwhile at the hospital, the donor is maintained on artificial support and the condition of each organ is carefully monitored by the hospital medical staff and the OPO procurement coordinator.
<br><br><b>Recovering and Transporting Organs:</b> The OPO representative arranges the arrival and departure times of the transplant surgical teams. After the surgical team arrives, the donor is taken to the operating room where organs and tissues are recovered in the same sterile and careful way as in any surgery. Tissue recoveries such as bone, cornea, and skin occur after organ recoveries. All incisions are surgically closed and usually do not interfere with open-casket funerals.
<br><br>Time is of the essence. Organs must get to their new homes very quickly as they can remain healthy only for short periods of time after removal from the donor. The OPO representative makes arrangements for the organs to get to the hospitals of the intended recipients. Method of transportation varies with the distance the organs are traveling, and most often involve commercial and contracted airplanes, helicopters, and ambulances.
<br><br><b>Transplanting the Organs:</b> The transplant operation takes place after the transport team arrives at the hospital with the new organ. Typically the transplant recipient is already at the hospital and may be in the operating room awaiting the arrival of the lifesaving organ. Surgical teams work around the clock as needed to transplant the new organs into the waiting recipients.
<br><br></big>
</body>
</html>