<!DOCTYPE html>
<html>
<head>
	<title></title>
	<?php 
	include_once 'html_commons/main-header.php';
	include_once 'html_commons/new-side.php';
	?>
</head>
<body background="images/background.jpg">
<h1>Selected Statutory and Regulatory History of Organ Transplantation</h1>
*Federal Legislation
<br><br>Links to the document are provided when available
<br><br><b>*2008—Public Law 110-413, Stephanie Tubbs Jones Gift of Life Medal Act of 2008</b> October 14, 2008—Establishes authority for the Department of Health and Human Services to issue a National Medal honoring organ donors.
<br><br><b>*2007—Public Law 110-144, Charlie W. Norwood Living Organ Donation Act</b>, December 21, 2007—Clarified that paired donation, as defined in the act, is not considered valuable consideration for purposes of Section 301 of NOTA; requires annual report that details the progress towards understanding the long-term health impacts of living donation.
<br><br><b>2006—Uniform Anatomical Gift Act,</b> 2006  —A model statute intended for adoption in every jurisdiction. This model law legally bars others from revoking the consent of a donor after death who legally registered as a donor during his or her lifetime (without an indication that the consent was no longer valid)..
<br><br><b>*2004—Public Law 108-216, Organ Donation and Recovery Improvement Act,</b> April 5, 2004—Expanded authorities of NOTA to include the authority to establish a grant program to provide reimbursement of travel and subsistence expenses for living organ donors and expanded other grant authorities. [GPO: Text, PDF]
<br><br><b>*2000—Public Law 106-310, Children’s Health Act, approved October 17, 2000</b>—Title XXI, Amended NOTA to require the OPTN to consider special issues concerning pediatric patients and organ allocation. [GPO: Text, PDF]
<br><br><b>*1999—Public Law 106-56, Organ Donor Leave Act</b> passed by Congress to allow federal employees to receive paid leave and serve as living organ or marrow donors. [GPO: Text, PDF]
<br><br><b>*1999—Public Law 106-170, Ticket to Work and Work Incentives Act,</b> December 17, 1999, Section 413—Delayed the effective date of the OPTN final rule. [GPO: Text, PDF]
<br><br><b>*1998—Public Law 106-113, 1999 Consolidated Appropriations Act,</b> November 29, 1999—Delayed the effective date of the OPTN final rule and made related amendments.  [GPO: Text, PDF]
<br><br><b>*1998—Final Rule</b> (63 Fed. Reg. 16296) Governing the operation of the OPTN was issued and published in the Federal Register. http://www.federalregister.gov/articles/1998/04/02/98-8191/organ-procurement-and-transplantation-network
<br><br><b>1996—Federal Register Notice</b> issued on November 13, 1996 (61 Fed. Reg. 58158)—Extended comment period for the OPTN Notice of Proposed Rulemaking and announced a public hearing on issues raised by the proposed regulation.
<br><br><b>1994—Notice of Proposed Rulemaking (NPRM) (59 Fed. Reg. 46482)</b>, September 8, 1994—Issued and published in the Federal Register proposing a regulation governing the operation of the Organ Procurement and Transplantation Network. http://www.federalregister.gov/articles/1994/09/08/94-21993-2/organ-procurement-and-transplantation-network-proposed-rule
<br><br><b>*1990—Public Law 101-616, The Transplant Amendments of 1990,</b> November 16, 1990—Provided for the establishment and maintenance of a National Bone Marrow Donor Registry. This law made other amendments to existing procurement and transplantation authorities.
<br><br><b>*1990—Public 101-274, Amendment to the Organ Transplant Amendments Act of 1988,</b> April 23, 1990—Deferred a certification requirement with respect to organ procurement organizations.
<br><br><b>*1989—Federal Register Notice</b> published by the Health Care Financing Administration (now the Centers for Medicare & Medicaid Services), Department of Health and Human Services on December 18, 1989 (54 FR 51802) —Clarified that no OPTN policies or issuances are “rules or requirements” of the OPTN for purposes of Section 1138 of the Social Security Act unless they have been formally approved by the Secretary.
<br><br><b>*1988—Public Law 100-607, The Health Omnibus Programs Extension of 1988,</b> November 4, 1988—Included the Organ Transplant Amendments of 1988, which made amendments to existing organ procurement and transplantation authorities.
<br><br><b>1987—Uniform Anatomical Gift Act,</b> 1987 Version, A model statute, intended for adoption in every jurisdiction. A revision to the original 1968 UAGA to deem a person's legal consent to donate before death irrevocable (without an indication that the consent was no longer valid).  
<br><br><b>*1987—Public Law 100-203, the Omnibus Budget Reconciliation Act of 1987,</b> December 22, 1987—Provided for the designation of pediatric hospitals that perform pediatric heart transplants as meeting certification requirements as heart transplant facilities in specified circumstances.
<br><br><b>*1987—Public Law 100-119, Balanced Budget and Emergency Deficit Control and Reaffirmation Act of 1987,</b> September 29, 1987—Delayed the effective date of § 1138(a) of the Social Security Act with respect to hospitals.
<br><br><b>*1986—Public Law 99-509, The Omnibus Budget Reconciliation Act of 1986,</b> October 21, 1986—Section 1138 of the Social Security Act - Included new requirements pertaining to organ procurement and transplantation and participation in the Medicare and Medicaid programs.
<br><br><b>*1985—Public Law 99-272, The Omnibus Reconciliation Act of 1985,</b> April 7, 1986—Required that states have written standards with regard to coverage of organ transplants in order to qualify for federal payments under Title XIX of the Social Security Act. 
<br><br><b>1984—Public Law 98-507, The National Organ Transplant Act (NOTA),</b> October 19, 1984—Provided for the establishment of the Task Force on Organ Transplantation, authorized the Secretary of Health and Human Services to make grants for organ procurement organizations, created the Organ Procurement and Transplantation Network (OPTN) to be run by contract by the Secretary of Health and Human Services, created the Scientific Registry of Transplant Recipients, and created an administrative unit within the Department of Health and Human Services to administer these activities. Section 301 of NOTA included the criminal prohibition against the exchange of organs for transplantation for valuable consideration.
<br><br><b>1980—The Uniform Determination of Death Act</b> - A model statute, intended for adoption in every jurisdiction, that replaced the Uniform Brain Death Act (which did not address traditional criteria for determining death). The Act states that an individual who has sustained either (1) irreversible cessation of circulatory or respiratory functions, or (2) irreversible cessation of all functions of the brain, including the brain stem, is dead. A determination of death must be made in accordance with accepted medical standards.
<br><br><b>1978—The Uniform Brain Death Act</b>-A model statute, intended for adoption in every jurisdiction. This model law established that the irreversible cessation of all functioning of the brain, including the brain stem, was death.
<br><br><b>*1978—Public Law 95-292, June 13, 1978</b> Amended the Social Security Act (End-Stage Renal Disease Program—Improvements) to provide for coverage under Medicare for end stage renal disease patients to receive kidney transplantation services.
<br><br><b>1973—Public Law 92-603, October 30, 1972</b>-Amended the Social Security Act to extend Medicare coverage to certain individuals with chronic renal disease. Such individuals were deemed to be disabled for the purposes of coverage under Parts A and B of Medicare. 
<br><br><b>1968—The Uniform Anatomical Gift Act (UAGA),</b> A model statute, intended for adoption in every jurisdiction. This law provided the legal foundation upon which human organs and tissues can be donated for transplantation by execution of a document of gift. Deemed a person's legal consent to donate before death sufficient under the law (without an indication that the consent was no longer valid). 

</body>
</html>