<!DOCTYPE html>
<html>
<head>
	<title>Transplants</title>
	<?php 
	include_once 'html_commons/main-header.php';
	include_once 'html_commons/new-side.php';
	?>
</head>
<body background="images/background.jpg">
<img src="images/images.jpg" align="right">
<h1 style="color: #191970;"><big><big><b>Types of Organ Transplants</b></big></big></h1>
<br><br>
<p><big><big>There are two main types of organ transplantation surgeries:</big></big>
<ul>
	<big><li><big>Deceased Donor Organ Transplants:</big></li> 
		<br>In deceased donor transplants, the donor organ isused from a personwhen he/she dies and his or her family donates the organ. Patients who need a deceased donor organ should get her/his name registered in the transplant registry of India, which maintains the database of all patients waiting for a deceased donor organ. In India the waiting time for a deceased donor transplant surgery is very long since there are many patients in India who are looking for a suitable deceased donor. 
	<br><br><li><big>Living Donor OrganTransplants:</big></li>
		<br>In a living donor organ transplantation surgery, the transplantsurgeons remove a portion or complete organfrom a healthy living person (donor) for transplantation into the patient (recipient). In India, the living donor has to be afirst degree relative of the recipient or the patient who is compatible and willing to make the organ donation. Before accepting a candidate as a donor, the transplant committee thoroughly evaluates the donor. It is mandatory to obtain approval of the authorization committee, appointed by the government to undergo transplant surgery. The transplant team determines the suitability of the donor for the donation after studying the various aspects and performing a series of medical tests.</big>

<h2>Some of the common Organ Transplant Surgeries performed in India</h2>
<br><br><big>
<ol>
<br><li><h3><b>Liver Transplant</b></h3></li>
<img src="images/liver1.png" alt="Liver" width="200" height="200" align="left" right="50px">
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspLiver failure has many causes, like liver cirrhosis, biliary duct atresia, cystic fibrosis, early-stage liver cancer, hemochromatosis, primary sclerosing cholangitis, primary biliary cirrhosis and Wilson's disease. Your liver can fail to perform its functions rapidly in a matter of weeks orit can also occur slowly over months or years. A liver transplant surgery is the last resort for patients suffering from liver failure. Liver transplant surgery is a meant for those patients who have end-stage liver failure and that cannot be controlled or treated using other any other treatment option. A liver transplant surgery is a procedure to remove the diseased liver of the patient and replace it with a portion of a healthy liver from a donor. Since only a portion of liver is removed from the donor body and the liver has the ability to grow, living-donor liver transplantation is possible.</p>
<br><li><h3><b>Kidney Transplant</b></h3></li>
<img src="images/kidney.png" alt="Kidney" width="200" height="170" align="right" >
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspYour kidneys filter and remove excess fluid and waste from the blood. This function is very important to your body. When the kidneys lose their ability to perform this function then dangerous levels of fluid and waste get accumulated in your body. This condition is known as kidney failure and over a period of time this becomes a life threatening condition. There are many causes for kidney failure. Over a period of time you may need either dialysis or a kidney transplant to stay alive.A kidney transplantation surgery is often the best treatment for kidney failure when medication and other conservative treatment options fail. In a kidney transplantation surgery your non- functioning kidney is replaced with a healthy kidney from your donor. Since only one donated kidney is needed to replace two failed kidneys, living-donor kidney transplantation is possible. </p>
<br><li><h3><b>Lung Transplant</b></h3></li>
<a href="kidney.php"><img src="images/lungs.png" alt="Kidney" width="200" height="170" align="left" ></a>
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspThe lungs help in providing your body with that vital oxygen while also removing carbon dioxide before it reaches a dangerous level. There are some diseases or conditions that can damage the lungs. This may adversely affect their ability of the lungs to function effectively. Some of the diseases of lung are Cystic fibrosis, Bronchiectasis, Emphysema or Chronic Obstructive Pulmonary Disease (COPD), Pulmonary Hypertension, Sarcoidosis etc. etc. A Lung disease can often be treated with medication or with special breathing devices. In some cases these options may not be fruitful and the reduced functioning of lungs may become life-threatening over a period of time. In such a condition your doctor might suggest a lung transplant surgery. Alung transplant is usually the last-resort treatment for lung failure.In a lung transplant surgery, the diseased or failing lung form your body is replaced with a healthy lung from a donor. Depending upon your medical condition, a lung transplant surgery may involve replacing one of the lungs or both of them. Single Lung Transplantation and Double Lung Transplantation are done at our network transplant centres in India.</p>
<br><li><h3><b>Heart Transplant </b></h3></li>
<a href="kidney.php"><img src="images/heart2.png" alt="Heart" width="200" height="170" align="right" ></a>
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspHeart Transplant Surgery is usually done as a last resort to treat end-stage heart failure or severe coronary artery disease in those patients who have tried medications or other surgeries, but their conditions haven't improved.In a heart transplant surgery a failing or diseased heart of the recipient is replaced with a healthier heart of a donor. Heart Transplant Surgery is a very high risk surgery. Hence it is very important to know the heart transplant process, the surgery itself, potential risks and follow-up care in order to make a decision to undergo a heart transplantation surgery.We have some of the leading heart transplant centres of India in our network.</p>
<br><li><h3><b>Cornea Transplant</b></h3></li>
<a href="kidney.php"><img src="images/eyes.png" alt="Cornea" width="200" height="170" align="left" ></a>
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspCornea is a transparent and dome-shaped surface of your eye that helps in most of the eye's focusing power. A Cornea Transplant is done when any damage to the cornea causes a drop in visionor pain that interferes with daily activities. In a cornea transplant surgery a part of cornea of the patient is replaced with corneal tissue from a donor. This surgery can help to improve the appearance of a damaged cornea, restore vision and reduce pain. A cornea transplant surgery is also called as Keratoplasty. </p>
<br><br><br><li><h3><b>Bone Marrow Transplant</b></h3></li>
<a href="kidney.php"><img src="images/bonemarrow1.png" alt="Bonemarrow" width="200" height="170" align="right" ></a>
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspBone marrow is a special soft, flexible, spongy, fatty tissue that houses stem cells and it is found inside a few large bones. The development and storage of 95% of the body's blood cells occurs in the bone marrow. Bone marrow transplant (BMT) is done to treat various diseases and cancer. A bone marrow transplant procedure may also be required when a person's bone marrow has been damaged or destroyed due to a disease or intense treatments of radiation or chemotherapy for cancer. Bone marrow transplant may be used in the treatment of diseases or conditions like Leukemia, Aplastic Anemia, Sickle Cell Anemia, Hurler's syndrome, Adrenoleukodystrophy etc. Bone marrow transplantation (BMT) involves taking out stem cells that are normally found in the bone marrow, filter those cells, and give them back either to the patient or to another person. The goal of BMT is to transfuse healthy bone marrow cells into a person after their unhealthy bone marrow has been removed. There are different types of bone marrow transplants depending on who the donor is. In India there are some very advanced and world-class centres for bone marrow transplantation. A bone marrow transplant is an expensive procedure and requires a longer stay in India.</p>
<br><li><h3><b>Pancreas Transplant</b></h3></li>
<a href="kidney.php"><img src="images/pancreas.png" alt="Pancreas" width="200" height="170" align="left" ></a>
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspPancreas is a vital organ that is located behind the lower part of your stomach. One of the very important functions of pancreas is the production of a hormone called insulin. Insulin regulates the absorption of glucose or sugar into cells of your body. When insulin is not produced in right quantity, it may cause the blood sugar to rise to dangerous levels in our body and such a condition gives rise to Type 1 Diabetes. Pancreas Transplant is done to replace anunhealthy pancreas of the patient with an healthy pancreas from a deceased donor. Most of the pancreas transplant surgeries are done to treat patients who suffering from Type 1 diabetes. Pancreas transplant is a very high risk surgery and hence it is typically done for only those people who have very serious diabetes complications and where all the other treatment options are not working out.</p>
<br><li><h3><b>Paediatric Organ Transplant</b></h3></li>
<a href="kidney.php"><img src="images/pediatricheart300x209.jpg" alt="Cornea" width="200" height="170" align="right" ></a>
<p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspOur network transplant centres in India also offer transplant surgery services for children suffering from various diseases or conditions that require a transplant surgery. The transplant centres have a multi-disciplinary team of doctors who have the required knowledge, experience and skills to perform complicated organ transplant in children and adolescents with life-threatening illnesses. The transplant centres have state-of-the-art medical and surgical care and gives a lot of importance is given to the dignity and respect, information sharing, participation and collaboration involving both the child and the family through the entire transplant procedure.</p>
 <br><br><br><br><br><br><br><br>
 <a href="registeration.php">Register now</a><br><br>
</ol>
 </body>
</html>